[shell]
program = "/opt/homebrew/bin/fish"
args = ["-l"]

[window]
decorations = "Transparent"
startup_mode = "Fullscreen"

[scrolling]
history = 0

[font]
size = 18.0

[font.normal]
family = "Noto Sans Mono"

[colors.primary]
background = "0x1d2021"
foreground = "0xd5c4a1"

[colors.cursor]
text = "0x1d2021"
cursor = "0xd5c4a1"

[colors.normal]
black = "0x1d2021"
red = "0xfb4934"
green = "0xb8bb26"
yellow = "0xfabd2f"
blue = "0x83a598"
magenta = "0xd3869b"
cyan = "0x8ec07c"
white = "0xd5c4a1"

[colors.bright]
black = "0x665c54"
red = "0xfe8019"
green = "0x3c3836"
yellow = "0x504945"
blue = "0xbdae93"
magenta = "0xebdbb2"
cyan = "0xd65d0e"
white = "0xfbf1c7"

[[colors.indexed_colors]]
index = 16
color = "#fe8019"

[[colors.indexed_colors]]
index = 17
color = "#d65d0e"

[[colors.indexed_colors]]
index = 18
color = "#3c3836"

[[colors.indexed_colors]]
index = 19
color = "#504945"

[[colors.indexed_colors]]
index = 20
color = "#bdae93"

[[colors.indexed_colors]]
index = 21
color = "#ebdbb2"

